version: 2
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  ci:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm ci

      - save_cache:
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Run linter
          command: npm run lint

      - run:
          name: Run tests
          command: |
            npm run test -- --coverage
            npx codecov@3.0.2

workflows:
  version: 2
  ci:
    jobs:
      - ci
